#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket-start-stop
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start aesdsocket daemon
### END INIT INFO

DAEMON="aesdsocket"
PIDFILE="/var/run/$DAEMON.pid"

case "$1" in
    start)
        echo "Starting $DAEMON"
        # -d tells your app to daemonize
        start-stop-daemon -S -n $DAEMON -a /usr/bin/$DAEMON -- -d
        ;;
    stop)
        echo "Stopping $DAEMON"
        # -s TERM sends the SIGTERM for graceful exit
        start-stop-daemon -K -n $DAEMON -s TERM
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
